spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



  datasource:
#    url: jdbc:postgresql://postgresql:5432/CP_Test
#    username: postgres
#    password: damiane1997
    driver-class-name: org.postgresql.Driver
#    hikari:
#      jdbc-url: jdbc:postgresql://postgresql:5432/CP_Test
#      auto-commit: false
#      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PRODUCT-SERVICE
  cloud:
    config:
      enabled: false

#  config:
#    import: configserver:http://config-server:9296
#    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka/


gcs:
  bucket:
    name: test_images_project


server:
  port: 8082